### ISSUE TITLE
what is differ projector_gray.py and projector.py  ? 

### ISSUE THREAD

**Issue by limhasic** [gunahn/StyleGAN2-ADA-pytorch-for-black-and-white-images#3]
it looks like same

**Comment by gunahn** [comment]
@limhasic I think projector_gray is for the image that only has 1 channel and projector.py is for image for 3 channels (RGB).

Thank you.

**Comment by limhasic** [comment]
I used pkl, which trained on gray_scaled images resized to 512x512.

!python projector.py
--outdir=/mnt/stylegan2-ada-pytorch/new_test \
--target=/noisy_gray_image.png \
--network=/auto4-kimg1000/network-snapshot-001000.pkl

But the following error occurred

```
> - [ ] - Loading networks from "/mnt/stylegan2-ada-pytorch/results/00007-new_image_grayscale-auto4-kimg1000/network-snapshot-001000.pkl"...
> - [ ] - target.shape :  torch.Size([3, 512, 512])
> - [ ] - G.img_channels 1
> - [ ] - G.img_resolution 512
> - [ ] - Traceback (most recent call last):
> - [ ] - File "projector_gray.py", line 213, in <module>
> - [ ] - run_projection() # pylint: disable=no-value-for-parameter
> - [ ] - File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
> - [ ] - return self.main(*args, **kwargs)
> - [ ] - File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
> - [ ] - rv = self.invoke(ctx)
> - [ ] - File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
> - [ ] - return ctx.invoke(self.callback, **ctx.params)
> - [ ] - File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
> - [ ] - return callback(*args, **kwargs)
> - [ ] - File "projector_gray.py", line 180, in run_projection
> - [ ] - projected_w_steps = project(
> - [ ] - File "projector_gray.py", line 45, in project
> - [ ] - assert target.shape == (G.img_channels, G.img_resolution, G.img_resolution)
> - [ ] - AssertionError
> - [ ] 
```

why target channel is 3?

**Comment by limhasic** [comment]
and i fix some codes but still occur error

```
Loading networks from "/mnt/stylegan2-ada-pytorch/results/00008-new_image_grayscale-auto4-kimg10/network-snapshot-000010.pkl"...
Traceback (most recent call last):
  File "projector_gray.py", line 215, in <module>
    run_projection() # pylint: disable=no-value-for-parameter
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "projector_gray.py", line 184, in run_projection
    target=torch.tensor(target_uint8.transpose([2, 0, 1]), device=device), # pylint: disable=not-callable
ValueError: axes don't match array
```

**Comment by limhasic** [comment]
i changed some code 

The source and dest orders of dataset_tool_gray are reversed, and is it correct to recompress the results and train the zip file?

like under 

```
!python dataset_tool_gray.py 
--source=/mnt/StyleGAN2-ADA-pytorch-for-gray-images/data_raw.zip 
--dest=/mnt/StyleGAN2-ADA-pytorch-for-gray-images/empty --width=512 --height=512  
--resize-filter=box

```

```
!python train.py 
--outdir=/mnt/stylegan2-ada-pytorch/results 
--gpus=4 
--data=/mnt/StyleGAN2-ADA-pytorch-for-gray-images/empty.zip 
--kimg 10 
--cfg=auto

```

**Comment by limhasic** [comment]
So why is the code the same? 

`!python projector_gray.py --outdir=out --target=~/mytargetimg.png --network= path to netwrok`

Has it ever been executed?
